'use strict';
const M=JMModel;
let preferences=M.defaults(),plugin=false,systemLanguage=navigator.language.startsWith('zh')?'zh-Hans':'en',settings=false,tab='外观',draft=null,editingFromSettings=false,reference=null,dragging=null,latest={snapshot:{},spectrum:[],vectors:[],history:[],source:{source:'idle',running:false,progress:-1}},lastError='',ready=false;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const language=()=>preferences.interfaceLanguage||systemLanguage;
const t=key=>language()==='en'?(JMTranslations[key]||key):key;
const fmt=(key,...args)=>t(key).replace(/\{(\d+)\}/g,(m,i)=>args[i]??m);
const post=(type,extra={})=>window.chrome?.webview?.postMessage({type,...extra});
const icons={wave:'M2 12c3 0 2-7 5-7s1 14 5 14 2-13 5-13 2 6 5 6',gear:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',close:'M6 6l12 12 M18 6 6 18',pin:'M9 3h6l-1 7 4 4H6l4-4z M12 14v8',pause:'M8 5v14 M16 5v14',play:'M7 4l13 8-13 8z',reset:'M4 9a8 8 0 1 1 0 6 M4 3v6h6',input:'M12 3v12 M8 4v7a4 4 0 0 0 8 0V4 M5 10v2a7 7 0 0 0 14 0v-2 M12 19v3',up:'m7 14 5-5 5 5',plus:'M12 5v14 M5 12h14'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.wave}"/></svg>`;
const button=(action,label,options='')=>`<button data-action="${action}" ${options}>${esc(t(label))}</button>`;
const iconButton=(action,label,name,extra='')=>`<button class="icon ${extra}" data-action="${action}" title="${esc(t(label))}" aria-label="${esc(t(label))}">${icon(name)}</button>`;
const layouts=()=>[M.standard,...preferences.layouts];
const currentLayout=()=>draft||layouts().find(l=>l.id===preferences.selected)||M.standard;
const layoutName=l=>l.id==='default'?t('默认'):l.name;
function persist(){preferences=M.sanitize(preferences);applyAppearance();post('preferences',{value:preferences});}
function applyAppearance(){const dark=preferences.theme==='dark'||(preferences.theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.lang=language()==='en'?'en':'zh-Hans';const transparency=matchMedia('(forced-colors:active)').matches?0:preferences.transparency;document.documentElement.style.setProperty('--solid',1-transparency/100);document.documentElement.style.setProperty('--glass',.82-transparency*.005);document.body.style.zoom=preferences.interfaceScale;$('app').style.height=(100/preferences.interfaceScale)+'vh';requestAnimationFrame(sizeGrid);}
function render(){closeMenu();applyAppearance();renderHeader();if(settings)renderSettings();else renderMeter();renderFooter();requestAnimationFrame(paint);}
function renderHeader(){const l=currentLayout();$('header').innerHTML=`<div class="brand">${icon('wave')}<span>Just Meter</span></div><div class="spacer"></div>${!settings&&!draft?`<button class="layout-name" data-action="layouts">${esc(layoutName(l))} <span class="subtle">⌄</span></button>`:''}${!plugin?iconButton('pin',preferences.pinned?'取消置顶':'窗口始终置顶','pin',preferences.pinned?'selected':''):''}${iconButton('settings',settings?'返回仪表':'设置',settings?'close':'gear')}`;$('header').querySelector('[data-action=settings]').disabled=!!draft;}
function renderMeter(){const l=currentLayout(),packed=M.pack(l.widgets);$('main').innerHTML=(draft?`<div class="editing glass">${icon('wave')}<input aria-label="${esc(t('布局名称'))}" id="layout-name" maxlength="40" value="${esc(draft.name)}"><small>${esc(t('拖动组件换位'))}</small><div class="spacer"></div>${button('add-widget','添加组件')}${button('cancel-edit','取消')}${button('save-edit','保存布局','class="primary"')}</div>`:'')+`<div class="grid-scroll"><div class="grid" id="grid">${packed.map(p=>widgetHTML(p.widget,p)).join('')}</div></div>`;sizeGrid();}
function sizeGrid(){const grid=$('grid');if(!grid)return;const height=grid.parentElement.clientHeight;grid.style.gridAutoRows=Math.max(210,(height-14)/2)+'px';}
const plot=(kind,w)=>`<div class="plot-wrap"><canvas data-plot="${kind}" data-widget="${esc(w.id)}" role="img" aria-label="${esc(t(M.titles[w.kind]))}"></canvas></div>`;
function widgetHTML(w,p){const subtitles={spectrum:'SPECTRUM',loudness:'EBU R128 · ITU-K',history:'LOUDNESS HISTORY',stereo:'STEREO FIELD',peaks:'PEAK LEVEL'};let content='';
 if(w.kind==='spectrum')content=plot('spectrum',w)+`<div class="axis">${[[20,'20 Hz'],[100,'100'],[1000,'1k'],[10000,'10k'],[20000,'20k']].map(([hz,label])=>`<span style="left:${Math.log(hz/20)/Math.log(1000)*100}%">${label}</span>`).join('')}</div>`+(w.fields.includes('参考曲线')?`<div class="chart-bottom">${button('reference',reference?'更新参考':'捕获参考','class="plain"')}${reference?button('clear-reference','清除','class="plain"'):''}<span class="spacer"></span><span>FFT 2048 · Hann</span></div>`:'');
 if(w.kind==='loudness')content=`<div class="readout"><small>${esc(t(w.fields[0]))}</small><div><span class="hero" data-reading="${esc(w.fields[0])}"></span><span class="unit">${w.fields[0]==='范围 LRA'?'LU':preferences.unit}</span></div><div class="secondary-metrics">${w.fields.slice(1).map(f=>`<div class="metric"><div><small>${esc(t(f))}</small><div class="metric-value" data-reading="${esc(f)}"></div></div><small>${f==='范围 LRA'?'LU':preferences.unit}</small></div>`).join('')}</div><div class="peak-footer"><span>True Peak</span><span data-reading="True Peak"></span><small>dBTP</small><span class="spacer"></span>${iconButton('clear-peak','清除峰值保持','reset')}</div></div>`;
 if(w.kind==='history')content=plot('history',w)+`<div class="legend">${w.fields.map(f=>`<span title="${esc(t(f))}"><i class="dot" style="background:${historyColor(f)}"></i>${esc(t(f))}</span>`).join('')}<span class="spacer"></span><span data-history-time></span></div>`;
 if(w.kind==='stereo')content=(w.fields.includes('向量图')?plot('stereo',w):'<span class="spacer"></span>')+(w.fields.includes('相关度')?`<div class="correlation-label"><span>${esc(t('相关度'))}</span><span data-correlation></span></div><div class="balance" style="flex:none"><i data-balance="correlation"></i></div>`:'')+(w.fields.includes('左右平衡')?'<div class="stereo-row"><span>L</span><div class="balance"><i data-balance="balance"></i></div><span>R</span></div>':'');
 if(w.kind==='peaks')content=w.fields.map(f=>`<div><small>${esc(f)}</small><div><span class="peak-large" data-reading="${f}"></span><span class="unit">${f==='True Peak'?'dBTP':'dBFS'}</span></div></div>`).join('')+`<div class="spacer"></div><div class="chart-bottom">${button('clear-peak','清除峰值保持','class="plain"')}</div>`;
 return `<section class="widget glass" data-id="${esc(w.id)}" ${draft?'draggable="true"':''} style="grid-column:${p.column+1}/span ${w.width};grid-row:${p.row+1}/span ${w.height}"><div class="widget-header">${draft?'<span class="subtle">☰</span>':''}<span class="widget-title">${esc(t(M.titles[w.kind]))}</span><span class="spacer"></span>${draft?button('widget-config',`${w.width} × ${w.height}`,`data-id="${esc(w.id)}"`):`<small>${subtitles[w.kind]}</small>`}</div>${content}</section>`;
}
function sourceText(){if(plugin)return latest.snapshot.active?fmt('宿主音频 · {0} kHz · {1} 声道',((latest.snapshot.sampleRate||0)/1000).toFixed(1),latest.snapshot.channels):t('等待宿主音频');const s=latest.source||{};if(s.error)return t('音频连接失败，请重新选择来源');if(s.source==='file')return fmt('分析 · {0}',s.file);if(s.source==='complete')return fmt('{0} · 分析完成',s.file);if(s.source==='system')return s.rate?`${t('系统音频')} · ${s.rate/1000} kHz · ${s.channels} ch`:t('系统音频 · 等待播放');if(s.source==='input')return s.rate?`${t('默认音频输入')} · ${s.rate/1000} kHz`:t('默认音频输入');if(s.source==='disconnected')return t('音频来源已断开');return t('选择音频来源，开始测量');}
function renderFooter(){const s=latest.snapshot||{},seconds=Math.max(0,Math.floor(s.seconds||0)),clock=[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(x=>String(x).padStart(2,'0')).join(':');$('footer').innerHTML=`${!plugin?iconButton('source','选择音频来源','input'):''}<i class="dot" style="opacity:${latest.source?.running||(plugin&&s.active)?1:.3}"></i><span class="source" title="${esc(sourceText())}">${esc(sourceText())}</span>${latest.source?.progress>=0?`<progress max="1" value="${latest.source.progress}"></progress>`:''}${s.droppedFrames?`<span class="over" title="${esc(t('音频队列发生丢帧，请重置后重新测量。'))}">⚠ ${s.droppedFrames}</span>`:''}<span class="spacer"></span><span class="clock">${clock}</span>${iconButton('pause',s.paused?'继续测量':'暂停测量',s.paused?'play':'pause')}${iconButton('reset','重置测量','reset')}`;}
const select=(key,options)=>`<select data-pref="${key}" aria-label="${esc(key)}">${options.map(([value,title])=>`<option value="${value}" ${String(key==='interfaceLanguage'?language():preferences[key])===String(value)?'selected':''}>${esc(t(title))}</option>`).join('')}</select>`;
const row=(title,detail,control)=>`<div class="setting-row"><div class="setting-label"><strong>${esc(t(title))}</strong><p>${esc(t(detail))}</p></div><div class="setting-control">${control}</div></div>`;
const numberInput=(key,label,unit,max=0)=>`<input type="number" data-pref="${key}" aria-label="${esc(t(label))}" min="-60" max="${max}" step="0.1" value="${preferences[key]}"> <small>${unit}</small>`;
function renderSettings(){let content='';
 if(tab==='外观')content=row('语言 / Language','切换后立即生效，并记住你的选择。',select('interfaceLanguage',[['zh-Hans','中文'],['en','English']]))+row('外观模式','跟随 Windows，或选择固定的浅色与深色外观。',select('theme',[['system','跟随系统'],['light','浅色'],['dark','深色']]))+row('界面缩放','缩放所有组件、文字和操作控件。窗口大小可以单独拖动调整。',select('interfaceScale',[[.5,'50%'],[.75,'75%'],[1,'100%'],[1.2,'120%']]))+row('毛玻璃透明度','调整窗口与组件的底色透明程度。文字、数字和图线保持清晰。',`<div id="transparency-value">${preferences.transparency}%</div><input type="range" min="0" max="85" value="${preferences.transparency}" data-pref="transparency" aria-label="${esc(t('界面透明度'))}"><div class="range-labels"><span>${esc(t('不透明'))}</span><span>${esc(t('通透'))}</span></div>`)+row('辅助功能','高对比度模式下自动使用实色背景。',`<small>${esc(t('跟随 Windows'))}</small>`);
 if(tab==='布局')content=`<div class="setting-row"><small>${esc(t('默认布局固定首位。自定义布局可自由编辑和排序。'))}</small><span class="spacer"></span>${button('new-layout','新建布局')}</div>`+layouts().map((l,i)=>`<div class="layout-row"><small>${String(i+1).padStart(2,'0')}</small><div class="info"><strong>${esc(layoutName(l))}</strong><small>${esc(l.id==='default'?t('系统预设 · 四个 1 × 1 组件'):fmt('{0} 个组件',l.widgets.length))}</small></div>${preferences.selected===l.id?`<small style="color:var(--accent)">${esc(t('使用中'))}</small>`:button('use-layout','使用',`data-id="${esc(l.id)}"`)}${button('edit-layout',l.id==='default'?'复制并编辑':'编辑',`data-id="${esc(l.id)}"`)}${l.id!=='default'?button('layout-options','•••',`data-id="${esc(l.id)}" aria-label="${esc(t('布局'))}"`):''}</div>`).join('');
 if(tab==='响度')content=row('测量标准','K 加权 · 400 ms 瞬时 · 3 s 短时 · 绝对与相对门限','<small>EBU R128 / BS.1770</small>')+row('响度单位','切换单位不会重置测量。范围始终使用 LU，真峰值使用 dBTP。',select('unit',[['LUFS','LUFS'],['LKFS','LKFS'],['LU','LU · 相对']]))+(preferences.unit==='LU'?row('相对参考','0 LU 对应的绝对响度。',numberInput('reference','参考值','LUFS')):'')+row('目标响度','用于历史图参考线，不改变音频。',numberInput('target','目标响度','LUFS'))+row('真峰值上限','超出此值时，峰值读数显示为橙色。',numberInput('peakLimit','真峰值上限','dBTP',6))+(plugin?row('跟随宿主播放','开启后，宿主停止时不再累计测量。',`<input type="checkbox" data-pref="followTransport" aria-label="${esc(t('跟随宿主播放'))}" ${preferences.followTransport?'checked':''}>`):'')+`<div class="notice">${esc(t('第一版使用 EBU 测量流程。WLM 的 DIAL / LM1 专用模式和告警计数将在后续版本接入。'))}</div>`;
 if(tab==='日志')content=row('导出测量日志','导出时间、瞬时、短时、整段响度和真峰值保持。CSV 始终使用 LUFS。',button('export','导出 CSV…',latest.history?.length?'':'disabled'))+row('历史容量','曲线和 CSV 保存最近 60 分钟，每 100 ms 一个记录；整段测量从上次重置开始累计。','<small>100 ms</small>')+(latest.snapshot.droppedFrames?`<div class="notice over">${esc(fmt('本次测量丢失 {0} 帧。请降低系统负载并重新测量。',latest.snapshot.droppedFrames))}</div>`:'');
 $('main').innerHTML=`<div class="settings"><div class="settings-heading"><h1>${esc(t('设置'))}</h1><small>${esc(t('让每一次测量，更合你的习惯。'))}</small></div><nav class="tabs" aria-label="${esc(t('设置分类'))}">${['外观','布局','响度','日志'].map(v=>button('tab',v,`data-tab="${v}" class="${v===tab?'active':''}"`)).join('')}</nav><div class="settings-scroll"><div class="settings-card glass">${content}</div></div>${button('about','关于 Just Meter','class="plain about-link"')}</div>`;
}
function closeMenu(){document.querySelector('.menu')?.remove();}
function menu(anchor,html){closeMenu();const node=document.createElement('div');node.className='menu glass';node.innerHTML=html;document.body.append(node);const r=anchor.getBoundingClientRect(),scale=preferences.interfaceScale;node.style.left=Math.max(8,Math.min(r.right/scale-node.offsetWidth,innerWidth/scale-node.offsetWidth-8))+'px';node.style.top=Math.max(8,Math.min(r.bottom/scale+7,innerHeight/scale-node.offsetHeight-8))+'px';node.querySelector('button')?.focus();}
function modal(html,extra=''){closeMenu();$('overlay').innerHTML=`<div class="modal-shade"><section role="dialog" aria-modal="true" class="dialog glass ${extra}">${html}</section></div>`;$('overlay').querySelector('input,button,a')?.focus();}
function closeModal(){$('overlay').innerHTML='';}
function beginEdit(layout){editingFromSettings=settings;draft=M.clone(layout||M.standard);if(draft.id==='default'){draft.id=M.id();draft.name=fmt('自定义布局 {0}',preferences.layouts.length+1);}settings=false;render();}
function finishEdit(save){if(save&&draft){draft.name=draft.name.trim().slice(0,40)||t('自定义布局');const i=preferences.layouts.findIndex(l=>l.id===draft.id);if(i<0)preferences.layouts.push(draft);else preferences.layouts[i]=draft;if(!editingFromSettings)preferences.selected=draft.id;persist();}draft=null;settings=editingFromSettings;closeModal();render();}
function configureWidget(id){const w=draft?.widgets.find(w=>w.id===id);if(!w)return;modal(`<h2>${esc(fmt('{0} · 组件设置',t(M.titles[w.kind])))}</h2><small>${esc(t('尺寸 · 宽 × 高'))}</small><div class="sizes">${[[1,1],[1,2],[2,1],[2,2]].map(([x,y])=>button('widget-size',`${x}×${y}`,`data-id="${esc(id)}" data-size="${x},${y}" class="${w.width===x&&w.height===y?'selected':''}"`)).join('')}</div><hr><small>${esc(t('显示数据 · 首项优先'))}</small>${[...w.fields,...M.fields[w.kind].filter(f=>!w.fields.includes(f))].map(f=>`<div class="field-row"><label><input type="checkbox" data-field="${esc(f)}" data-id="${esc(id)}" ${w.fields.includes(f)?'checked':''}>${esc(t(f))}</label>${w.fields.indexOf(f)>0?button('field-up','↑',`data-id="${esc(id)}" data-field="${esc(f)}" aria-label="${esc(t('向前移动'))}"`):''}</div>`).join('')}<hr><div class="dialog-actions">${button('remove-widget','移除组件',`class="danger" data-id="${esc(id)}" ${draft.widgets.length<=1?'disabled':''}`)}<span class="spacer"></span>${button('close-modal','完成','class="primary"')}</div>`);}
function error(message){modal(`<h2>Just Meter</h2><div class="error-text">${esc(message)}</div><div class="dialog-actions">${button('close-modal','好','class="primary"')}</div>`);}
document.addEventListener('click',event=>{
 const b=event.target.closest('[data-action]');if(!b){if(!event.target.closest('.menu'))closeMenu();return;}const a=b.dataset.action,id=b.dataset.id,l=layouts().find(l=>l.id===id);const w=draft?.widgets.find(w=>w.id===id);
 if(a==='settings'){settings=!settings;render();}else if(a==='pin'){preferences.pinned=!preferences.pinned;persist();renderHeader();}
 else if(a==='layouts')menu(b,`<small>${esc(t('布局'))}</small>${layouts().map(l=>button('use-layout',layoutName(l),`data-id="${esc(l.id)}"`)).join('')}<hr>${button('new-layout','新建布局…')}${button('edit-layout',preferences.selected==='default'?'复制默认并编辑…':'编辑当前布局…',`data-id="${esc(preferences.selected)}"`)}`);
 else if(a==='use-layout'){preferences.selected=id;persist();render();}else if(a==='new-layout')beginEdit(null);else if(a==='edit-layout')beginEdit(l);
 else if(a==='save-edit')finishEdit(true);else if(a==='cancel-edit')finishEdit(false);
 else if(a==='add-widget')menu(b,Object.keys(M.fields).map(k=>button('insert-widget',M.titles[k],`data-kind="${k}" ${draft.widgets.length>=64?'disabled':''}`)).join(''));
 else if(a==='insert-widget'&&draft&&draft.widgets.length<64){draft.widgets.push(M.widget(b.dataset.kind));render();}
 else if(a==='widget-config')configureWidget(id);else if(a==='widget-size'&&w){[w.width,w.height]=b.dataset.size.split(',').map(Number);renderMeter();configureWidget(id);paint();}
 else if(a==='field-up'&&w){const i=w.fields.indexOf(b.dataset.field);if(i>0)[w.fields[i],w.fields[i-1]]=[w.fields[i-1],w.fields[i]];renderMeter();configureWidget(id);paint();}
 else if(a==='remove-widget'&&draft?.widgets.length>1){draft.widgets=draft.widgets.filter(w=>w.id!==id);closeModal();renderMeter();paint();}
 else if(a==='layout-options'&&l&&l.id!=='default'){const i=preferences.layouts.indexOf(l);menu(b,button('rename-layout','重命名…',`data-id="${esc(id)}"`)+button('layout-up','上移',`data-id="${esc(id)}" ${i===0?'disabled':''}`)+button('layout-down','下移',`data-id="${esc(id)}" ${i===preferences.layouts.length-1?'disabled':''}`)+'<hr>'+button('delete-layout','删除…',`class="danger" data-id="${esc(id)}"`));}
 else if(a==='rename-layout'&&l&&id!=='default')modal(`<h2>${esc(t('重命名布局'))}</h2><input id="rename-value" type="text" maxlength="40" value="${esc(l.name)}" aria-label="${esc(t('名称'))}"><div class="dialog-actions">${button('close-modal','取消')}${button('save-name','保存',`class="primary" data-id="${esc(id)}"`)}</div>`);
 else if(a==='save-name'&&l&&id!=='default'){const name=$('rename-value').value.trim();if(name){l.name=name.slice(0,40);persist();closeModal();render();}}
 else if((a==='layout-up'||a==='layout-down')&&l&&id!=='default'){const i=preferences.layouts.indexOf(l),j=i+(a==='layout-up'?-1:1);if(j>=0&&j<preferences.layouts.length){[preferences.layouts[i],preferences.layouts[j]]=[preferences.layouts[j],preferences.layouts[i]];persist();render();}}
 else if(a==='delete-layout'&&l&&id!=='default')modal(`<h2>${esc(t('删除布局？'))}</h2><p>${esc(fmt('“{0}”将被删除。删除当前布局后会返回默认布局。',l.name))}</p><div class="dialog-actions">${button('close-modal','取消')}${button('confirm-delete','删除',`class="danger" data-id="${esc(id)}"`)}</div>`);
 else if(a==='confirm-delete'&&id!=='default'){preferences.layouts=preferences.layouts.filter(l=>l.id!==id);persist();closeModal();render();}
 else if(a==='tab'){tab=b.dataset.tab;renderSettings();}else if(a==='close-modal')closeModal();
 else if(a==='about')modal(`<h2>Yee Huang</h2><a href="#" data-action="email">yeehuang2002@163.com</a><div class="dialog-actions">${button('close-modal','完成','class="primary"')}</div>`,'about');
 else if(a==='email'){event.preventDefault();post('email');}
 else if(a==='source')menu(b,button('file','导入音频文件…')+button('system','系统音频')+button('input','默认音频输入')+(latest.source?.running?'<hr>'+button('disconnect','断开音频来源'):''));
 else if(['file','system','input','disconnect','export','clear-peak','pause'].includes(a)){closeMenu();if(a==='disconnect')latest.source={source:'disconnected',running:false,progress:-1};post(a);}
 else if(a==='reset'){reference=null;post('reset');if(!settings){renderMeter();paint();}}
 else if(a==='reference'){reference=latest.spectrum.slice();renderMeter();paint();}else if(a==='clear-reference'){reference=null;renderMeter();paint();}
});
document.addEventListener('input',event=>{const el=event.target;if(el.id==='layout-name'&&draft)draft.name=el.value;if(el.dataset.pref==='transparency'){preferences.transparency=Number(el.value);$('transparency-value').textContent=el.value+'%';persist();paint();}});
document.addEventListener('change',event=>{const el=event.target,key=el.dataset.pref;if(key){preferences[key]=el.type==='checkbox'?el.checked:['interfaceScale','transparency','reference','target','peakLimit'].includes(key)?Number(el.value):el.value;persist();if(key!=='transparency')render();}if(el.dataset.field&&el.type==='checkbox'){const w=draft?.widgets.find(w=>w.id===el.dataset.id);if(w){const f=el.dataset.field;if(el.checked&&!w.fields.includes(f))w.fields.push(f);else if(!el.checked&&w.fields.length>1)w.fields=w.fields.filter(x=>x!==f);renderMeter();configureWidget(w.id);paint();}}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if($('overlay').children.length)closeModal();else if(document.querySelector('.menu'))closeMenu();else if(settings){settings=false;render();}}const typing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName);if((event.ctrlKey||event.metaKey)&&!typing){if(event.key==='o'&&!plugin){event.preventDefault();post('file');}if(event.key==='e'){event.preventDefault();post('export');}if(event.key===','){event.preventDefault();settings=true;render();}}if(event.key==='Tab'&&$('overlay').children.length){const focusable=[...$('overlay').querySelectorAll('button:not(:disabled),input:not(:disabled),a[href]')];if(event.shiftKey&&document.activeElement===focusable[0]){event.preventDefault();focusable.at(-1)?.focus();}else if(!event.shiftKey&&document.activeElement===focusable.at(-1)){event.preventDefault();focusable[0]?.focus();}}});
document.addEventListener('dragstart',event=>{const tile=event.target.closest('.widget');if(!draft||!tile){event.preventDefault();return;}dragging=tile.dataset.id;event.dataTransfer.setData('text/plain',dragging);event.dataTransfer.effectAllowed='move';tile.classList.add('dragging');});
document.addEventListener('dragover',event=>{if(dragging&&event.target.closest('.widget')){event.preventDefault();event.dataTransfer.dropEffect='move';}});
document.addEventListener('drop',event=>{const target=event.target.closest('.widget');if(!draft||!dragging||!target)return;event.preventDefault();const i=draft.widgets.findIndex(w=>w.id===dragging),j=draft.widgets.findIndex(w=>w.id===target.dataset.id);if(i>=0&&j>=0&&i!==j)draft.widgets.splice(j,0,draft.widgets.splice(i,1)[0]);dragging=null;renderMeter();paint();});
document.addEventListener('dragend',()=>{dragging=null;document.querySelectorAll('.dragging').forEach(e=>e.classList.remove('dragging'));});
function historyColor(f){return f==='短时 S'?'#38bac9':f==='瞬时 M'?'#829099':'#a195d6';}
function reading(field){const s=latest.snapshot||{},key={'整段 I':'integrated','瞬时 M':'momentary','短时 S':'shortTerm','范围 LRA':'range','最大瞬时':'maxMomentary','True Peak':'truePeak','Sample Peak':'samplePeak'}[field];return M.formatted(s[key],preferences,!['范围 LRA','True Peak','Sample Peak'].includes(field));}
function paint(){document.querySelectorAll('[data-reading]').forEach(e=>{e.textContent=reading(e.dataset.reading);e.classList.toggle('over',e.dataset.reading==='True Peak'&&(latest.snapshot.truePeak??-Infinity)>preferences.peakLimit);});document.querySelectorAll('[data-correlation]').forEach(e=>e.textContent=latest.snapshot.active?((latest.snapshot.correlation||0)>=0?'+':'')+(latest.snapshot.correlation||0).toFixed(2):'—');document.querySelectorAll('[data-balance]').forEach(e=>{const value=Math.max(-1,Math.min(1,latest.snapshot[e.dataset.balance]||0));e.style.left=`calc(${(value+1)*50}% - ${(value+1)*2}px)`;e.style.background=e.dataset.balance==='correlation'&&value<0?'var(--orange)':'var(--accent)';});document.querySelectorAll('[data-history-time]').forEach(e=>e.textContent=latest.history.length?`${Math.floor(latest.history[0].time)}–${Math.floor(latest.snapshot.seconds||0)} s`:t('等待音频'));document.querySelectorAll('[data-plot]').forEach(drawPlot);}
function drawPlot(canvas){const w=currentLayout().widgets.find(w=>w.id===canvas.dataset.widget);if(!w)return;const width=canvas.clientWidth,height=canvas.clientHeight;if(width<1||height<1)return;const ratio=devicePixelRatio||1;if(canvas.width!==Math.round(width*ratio)||canvas.height!==Math.round(height*ratio)){canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);}const c=canvas.getContext('2d');c.setTransform(ratio,0,0,ratio,0,0);c.clearRect(0,0,width,height);const theme=getComputedStyle(document.documentElement),muted=theme.getPropertyValue('--muted'),line=theme.getPropertyValue('--line');c.font='9px Segoe UI';c.lineWidth=1;
 const path=(values,xy,color,dash=[],fill=false)=>{c.beginPath();let started=false;values.forEach((value,i)=>{if(!Number.isFinite(value)){started=false;return;}const [x,y]=xy(value,i);if(!started)c.moveTo(x,y);else c.lineTo(x,y);started=true;});c.strokeStyle=color;c.lineWidth=1.6;c.setLineDash(dash);c.stroke();c.setLineDash([]);if(fill&&values.length){c.lineTo(width,height);c.lineTo(0,height);c.closePath();const g=c.createLinearGradient(0,0,0,height);g.addColorStop(0,'#38bac951');g.addColorStop(1,'#38bac903');c.fillStyle=g;c.fill();}};
 if(w.kind==='spectrum'){for(let i=0;i<=4;i++){const y=i*height/4;c.beginPath();c.moveTo(0,y);c.lineTo(width,y);c.strokeStyle=line;c.lineWidth=1;c.stroke();c.fillStyle=muted;c.fillText(String(-i*25),width-27,Math.min(height-3,y+10));}const xy=(v,i)=>[i*width/63,(1-(Math.max(-100,Math.min(0,v))+100)/100)*height];if(w.fields.includes('参考曲线')&&reference)path(reference,xy,muted,[4,4]);if(w.fields.includes('实时曲线'))path(latest.spectrum,xy,'#38bac9',[],true);}
 if(w.kind==='history'){const left=29,y=v=>(1-(Math.max(-60,Math.min(0,v))+60)/60)*height;for(let level=0;level>=-60;level-=15){c.beginPath();c.moveTo(left,y(level));c.lineTo(width,y(level));c.strokeStyle=line;c.lineWidth=1;c.stroke();c.fillStyle=muted;c.fillText(M.formatted(level,preferences),0,Math.min(height-3,y(level)+8));}c.beginPath();c.moveTo(left,y(preferences.target));c.lineTo(width,y(preferences.target));c.setLineDash([3,5]);c.strokeStyle='#38bac955';c.stroke();c.setLineDash([]);for(const f of w.fields){const key=f==='短时 S'?'shortTerm':f==='瞬时 M'?'momentary':'integrated';path(latest.history.map(h=>h[key]),(v,i)=>[left+i/Math.max(1,latest.history.length-1)*(width-left),y(v)],historyColor(f));}if(!latest.history.length){c.fillStyle=muted;c.textAlign='center';c.font='12px Segoe UI';c.fillText(t('等待音频输入'),width/2,height/2);c.textAlign='left';}}
 if(w.kind==='stereo'){const x=width/2,y=height/2,r=Math.max(0,Math.min(x,y)-6);c.beginPath();c.arc(x,y,r,0,Math.PI*2);for(const sign of[-1,1]){c.moveTo(x-r*.707,y-r*.707*sign);c.lineTo(x+r*.707,y+r*.707*sign);}c.moveTo(x,y-r);c.lineTo(x,y+r);c.strokeStyle=line;c.lineWidth=1;c.stroke();c.beginPath();for(let i=0;i<latest.vectors.length/2;i++){const l=latest.vectors[i*2],rr=latest.vectors[i*2+1],xx=x+(rr-l)*.7*r,yy=y-(l+rr)*.7*r;if(i===0)c.moveTo(xx,yy);else c.lineTo(xx,yy);}c.strokeStyle='#38bac9cc';c.stroke();}
}
function receive(message){if(message.type==='state'){plugin=!!message.plugin;systemLanguage=message.language||systemLanguage;preferences=M.sanitize(message.preferences);ready=true;render();}else if(message.type==='meter'){latest={...latest,...message};renderFooter();paint();if(message.source?.error&&message.source.error!==lastError){lastError=message.source.error;error(t('音频连接失败，请重新选择来源')+'\n'+lastError);}if(!message.source?.error)lastError='';}else if(message.type==='error')error(message.message);}
window.chrome?.webview?.addEventListener('message',event=>receive(event.data));
window.addEventListener('resize',()=>{sizeGrid();paint();});matchMedia('(prefers-color-scheme:dark)').addEventListener('change',()=>{applyAppearance();paint();});
render();post('ready');
