enable_language(RC)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(SMTG_USE_STATIC_CRT ON CACHE BOOL "" FORCE)
set(SMTG_ENABLE_VST3_PLUGIN_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SMTG_ENABLE_VST3_HOSTING_EXAMPLES ON CACHE BOOL "" FORCE)
set(SMTG_ENABLE_VSTGUI_SUPPORT OFF CACHE BOOL "" FORCE)
set(SMTG_CREATE_PLUGIN_LINK OFF CACHE BOOL "" FORCE)
set(SMTG_CREATE_BUNDLE_FOR_WINDOWS ON CACHE BOOL "" FORCE)
set(SMTG_RUN_VST_VALIDATOR OFF CACHE BOOL "" FORCE)
set(SMTG_CREATE_MODULE_INFO OFF CACHE BOOL "" FORCE)
add_compile_definitions(UNICODE _UNICODE NOMINMAX WIN32_LEAN_AND_MEAN _WIN32_WINNT=0x0A00 _CRT_SECURE_NO_WARNINGS)
add_compile_options($<$<COMPILE_LANGUAGE:CXX>:/utf-8>)
add_subdirectory(vendor/vst3sdk)
add_library(JustMeterDSP STATIC Sources/DSP/MeterCore.cpp vendor/libebur128/ebur128/ebur128.c)
target_include_directories(JustMeterDSP PUBLIC Sources/DSP PRIVATE vendor/libebur128/ebur128 vendor/libebur128/ebur128/queue)
target_compile_definitions(JustMeterDSP PRIVATE _USE_MATH_DEFINES)
set(JM_WEBVIEW_ROOT "${CMAKE_SOURCE_DIR}/vendor/webview2/build/native")
if(NOT EXISTS "${JM_WEBVIEW_ROOT}/include/WebView2.h")
    message(FATAL_ERROR "Run scripts/bootstrap-windows.ps1 first")
endif()
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/scripts/embed-windows-ui.py" "${CMAKE_BINARY_DIR}/generated" COMMAND_ERROR_IS_FATAL ANY)
set(JM_HTML "${CMAKE_BINARY_DIR}/generated/MeterWeb.html")
set(JM_ICON "${CMAKE_BINARY_DIR}/generated/JustMeter.ico")
set(JM_MANIFEST "${CMAKE_SOURCE_DIR}/Sources/Windows/JustMeter.manifest")
configure_file(Sources/Windows/Resources.rc.in generated/Resources.rc @ONLY)
add_library(JustMeterWindows STATIC Sources/Windows/Editor.cpp Sources/Windows/AudioCapture.cpp Sources/Windows/AIFFReader.cpp)
target_include_directories(JustMeterWindows PUBLIC Sources/Windows Sources/DSP "${JM_WEBVIEW_ROOT}/include" vendor/json)
target_link_libraries(JustMeterWindows PUBLIC JustMeterDSP "${JM_WEBVIEW_ROOT}/x64/WebView2LoaderStatic.lib" ole32 oleaut32 uuid shlwapi shell32 comdlg32 dwmapi advapi32 mfplat mfreadwrite mfuuid propsys ksuser version)
add_executable(JustMeterApp WIN32 Sources/Windows/main.cpp "${CMAKE_BINARY_DIR}/generated/Resources.rc")
target_link_libraries(JustMeterApp PRIVATE JustMeterWindows)
target_link_options(JustMeterApp PRIVATE /MANIFEST:NO)
set_target_properties(JustMeterApp PROPERTIES OUTPUT_NAME "Just Meter")
smtg_add_vst3plugin(JustMeter Sources/Plugin/JustMeter.cpp vendor/vst3sdk/public.sdk/source/vst/vstsinglecomponenteffect.cpp vendor/vst3sdk/public.sdk/source/main/dllmain.cpp "${CMAKE_BINARY_DIR}/generated/Resources.rc")
target_link_libraries(JustMeter PRIVATE sdk JustMeterWindows)
target_link_options(JustMeter PRIVATE /MANIFEST:NO)
enable_testing()
add_executable(MeterCoreTests Tests/meter_tests.cpp)
target_link_libraries(MeterCoreTests PRIVATE JustMeterDSP)
target_compile_options(MeterCoreTests PRIVATE /UNDEBUG)
file(MAKE_DIRECTORY "${CMAKE_SOURCE_DIR}/build")
add_test(NAME DSP COMMAND MeterCoreTests)
set_tests_properties(DSP PROPERTIES WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}")
add_executable(WindowsAudioTests Tests/windows_audio_tests.cpp)
target_link_libraries(WindowsAudioTests PRIVATE JustMeterWindows)
target_compile_options(WindowsAudioTests PRIVATE /UNDEBUG)
add_test(NAME WindowsFileAnalysis COMMAND WindowsAudioTests "${CMAKE_SOURCE_DIR}/Tests/Reference-1kHz-stereo-minus20dBFS.wav")
add_executable(WindowsPluginHost Tests/windows_plugin_host.cpp)
target_link_libraries(WindowsPluginHost PRIVATE sdk sdk_hosting ole32)
target_compile_options(WindowsPluginHost PRIVATE /UNDEBUG)

add_test(NAME WindowsAIFFAnalysis COMMAND WindowsAudioTests "${CMAKE_SOURCE_DIR}/build/Reference-中文.aiff")
